language: node_js

node_js:
  - lts/*

script:
  - pnpm run lint
  - pnpm run build

cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -fsSL https://get.pnpm.io/install.sh | sh -
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
